include: package:flutter_lints/flutter.yaml
code-style:

linter:
  rules:
    library_private_types_in_public_api: false
    prefer_const_constructors: true
    non_constant_identifier_names: false
    prefer_relative_imports: true
    require_trailing_commas: false

analyzer:
  errors:
    prefer_const_constructors: warning

formatter:
  page_width: 150
  trailing_commas: preserve
