name: victory
publish_to: none
description: "A Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  get_storage: ^2.1.1
  get: ^4.7.2
  extended_image: ^10.0.1
  intl: ^0.20.2
  material_symbols_icons: ^4.2873.0
  restart_app: ^1.3.2
  talker_flutter: ^5.0.1
  floating_draggable_widget: ^2.3.0
  bot_toast: ^4.1.3
  scaled_app: ^2.3.0
  lottie: ^3.3.2
  pull_to_refresh: ^2.0.0
  carousel_slider: ^5.1.1
  package_info_plus: ^9.0.0
  # move_to_background: ^1.0.2
  vector_graphics: ^1.1.19
  move_to_back: ^3.0.0
  audioplayers: ^6.5.1
  flutter_cache_manager: ^3.4.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  animate_do: ^4.2.0
  # animated_flip_counter: ^0.3.4
  # flutter_animate: ^4.5.2
  expand_tap_area: ^1.1.1
  encrypt: ^5.0.3
  skeletonizer: ^2.1.0+1
  cached_network_image: ^3.4.1
  mobile_device_identifier: ^0.0.3
  advertising_id: ^2.7.1
  uuid: ^4.5.1
  animated_digit: ^3.3.1+2
  talker_dio_logger: ^5.0.1
  defer_pointer: ^0.0.2
  simple_animations: ^5.2.0
  # roulette: ^0.2.0
  tutorial_coach_mark: ^1.3.1
  slide_countdown: ^2.0.2
  # stroke_text: ^1.0.0
  textuality: ^0.0.4

dependency_overrides:
  lottie: ^3.3.2
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  vector_graphics_compiler: ^1.1.19

flutter:
  uses-material-design: true
  assets:
    # - shorebird.yaml
    # - assets/htmls/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - path: assets/svg/
      transformers:
        - package: vector_graphics_compiler

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/iconfont/iconfont.ttf
