export default {
    home: 'home',
    foru: 'foru',
    promos: 'promos',
    funds: 'funds',
    me: 'me',
    message: 'message',
    messageDetail: 'messageDetail',
    more: 'more',
    favorites: 'favorites',
    invitation: 'invitation',
    vip: 'vip',
    account: 'account',
    turnover: 'turnover',
    turnoverHistory: 'turnover-history',
} as const
